print('x1')
x1 = int(input())
print('x2')
x2 = int(input())
print('x3')
x3 = int(input())
print('x4')
x4 = int(input())
print('x5')
x5 = int(input())
print('x6')
x6 = int(input())
print('x7')
x7 = int(input())
X = (x1 and (not x1 and not x2) and x3 and not x4 and x5 and not x6 and x7)
if X == 1:
    print('True')
else:
    print('False')
