print('x1')
x1 = int(input())
print('x2')
x2 = int(input())
print('x3')
x3 = int(input())
print('x4')
x4 = int(input())
print('x5')
x5 = int(input())
print('x6')
x6 = int(input())
print('x7')
x7 = int(input())
print('x8')
x8 = int(input())
print('x9')
x9 = int(input())
print('x10')
x10 = int(input())
print('1)', (x1 or not x2) and (x3 or not x4) and x5 and not x6 and x7 and x8 and not x9 and x10)
print('2)', (x1 and not x2) or (x3 and not x4) or x5 or not x6 and x7 or x8 or not x9 or x10)
print('3)', (not x1 and x2) or (not x3 and x4) or not x5 or x6 or not x7 or not x8 or x9 or not x10)
print('4)', (not x1 or x2) and (not x3 or x4) and not x5 and x6 and not x7 and not x8 and x9 and not x10)
